name: 🛒 Abandoned Cart Recovery
description: Detects abandoned carts and triggers optimal recovery actions based on customer segments and abandonment reasons.
enabled: true
triggers:
- type: manual

steps:
- name: detect_carts
  type: elasticsearch.search
  with:
    index: "cart_events"
    size: 0
    query:
      bool:
        must:
          - range:
              "@timestamp":
                gte: "now-1440m"
          - term:
              event_type: add_to_cart
        must_not:
          - exists:
              field: checkout_completed
    aggs:
      carts:
        terms:
          field: cart_id
          size: 20
                  gte: "now-1440m"
            - term:
                event_type: add_to_cart
          must_not:
            - exists:
                field: checkout_completed
      aggs:
        carts:
          terms:
            field: cart_id
            size: 20

- name: check_carts_exist
  type: condition
  with:
    if: "{{detect_carts.output.aggregations.carts.buckets | length > 0}}"

- name: set_cart_id
  type: data.set
  with:
    value: "{% if detect_carts.output.aggregations.carts.buckets | length > 0 %}{{detect_carts.output.aggregations.carts.buckets.0.key}}{% else %}unknown{% endif %}"

- name: analyze_abandonment
  type: data.set
  connector-id: elasticsearch-query
  with:
    index: checkout_events
    body:
      size: 10
      query:
        term:
          cart_id: "{{set_cart_id.value}}"
      sort:
        - "@timestamp":
            order: desc

- name: set_customer_id
  type: data.set
  with:
    value: "{% if analyze_abandonment.output.hits.hits | length > 0 %}{{analyze_abandonment.output.hits.hits.0._source.customer_id}}{% else %}unknown{% endif %}"

- name: get_customer
  type: data.set
  connector-id: elasticsearch-query
  with:
    index: customer_profiles
    body:
      size: 1
      query:
        term:
          customer_id: "{{set_customer_id.value}}"

- name: set_email
  type: data.set
  with:
    value: "{% if get_customer.output.hits.hits | length > 0 %}{{get_customer.output.hits.hits.0._source.email}}{% else %}unknown@example.com{% endif %}"

- name: decide_action
  type: data.set
  with:
    value: |
      {% set customer_segment = "standard" %}
      {% set abandonment_step = "general" %}
      {% set cart_count = 0 %}
      
      {% if get_customer.output.hits.hits | length > 0 %}
        {% set customer_segment = get_customer.output.hits.hits.0._source.segment %}
      {% endif %}
      
      {% if analyze_abandonment.output.hits.hits | length > 0 %}
        {% set abandonment_step = analyze_abandonment.output.hits.hits.0._source.step %}
      {% endif %}
      
      {% if detect_carts.output.aggregations.carts.buckets | length > 0 %}
        {% set cart_count = detect_carts.output.aggregations.carts.buckets.0.doc_count %}
      {% endif %}

      {% if customer_segment == "vip" %}
        {% if abandonment_step == "payment_failed" %}
          payment_retry
        {% else %}
          {% if abandonment_step == "shipping_failed" %}
            free_shipping
          {% else %}
            {% if cart_count > 500 %}
              discount
            {% else %}
              free_shipping
            {% endif %}
          {% endif %}
        {% endif %}
      {% else %}
        {% if customer_segment == "high_fraud_risk" %}
          {% if abandonment_step == "payment_failed" %}
            blocked
          {% else %}
            reminder
          {% endif %}
        {% else %}
          {% if customer_segment == "standard" %}
            {% if abandonment_step == "payment_failed" %}
              payment_retry
            {% else %}
              {% if abandonment_step == "shipping_failed" %}
                free_shipping
              {% else %}
                {% if cart_count > 300 %}
                  discount
                {% else %}
                  reminder
                {% endif %}
              {% endif %}
            {% endif %}
          {% else %}
            reminder
          {% endif %}
        {% endif %}
      {% endif %}

- name: set_action
  type: data.set
  with:
    value: "{{decide_action.output}}"

- name: trigger_action
  type: data.set
  connector-id: http
  with:
    url: "https://api.example.com/send"
    method: POST
    headers:
      Content-Type: application/json
    body:
      to: "{{set_email.value}}"
      action: "{{set_action.value}}"

- name: set_timestamp
  type: data.set
  with:
    value: "{{now}}"

- name: record_attempt
  type: data.set
  connector-id: elasticsearch-query
  with:
    index: recovery_history
    body:
      cart_id: "{{set_cart_id.value}}"
      customer_id: "{{set_customer_id.value}}"
      action:
        type: "{{set_action.value}}"
      sent_at: "{{set_timestamp.value}}"
      outcome:
        status: "pending"